---
- name: Install required packages for MongoDB Server
  package:
    name:
      - mongodb-server
      - mongodb-2.6.12-6.el7.x86_64
    state: latest
  notify:
    - Enable and start mongod
  tags:
    - deploy
- name: Templating dbconnect.j2 to application database
  template:
    src: dbconnect.j2
    dest: /home/{{ app_user_name }}/app/{{ git_repo }}/dbconnect.js
    owner: "{{ app_user_name }}"
    mode: "0755"
  tags:
    - deploy

