---
- name: gathering status information for Nginx and Chatapp Service (skipped if unavailble)
  service_facts:
  register: ec2_services
  tags:
    - info
- debug:
    msg: " Nginx Service status: {{ ec2_services.ansible_facts.services['nginx.service']['state'] }}"
  tags:
    - info
  when: ec2_services.ansible_facts.services['nginx.service'] is defined
- debug:
    msg: " Chatapp Service status: {{ ec2_services.ansible_facts.services['chatapp.service']['state'] }}"
  tags:
    - info
  when: ec2_services.ansible_facts.services['chatapp.service'] is defined
