---
- name: Install Nodejs
  package:
    name: nodejs
    state: present
  tags:
    - deploy
- name: Updating packages based on package.json to their latest version.
  npm:
    path: /home/{{ app_user_name }}/app/{{ git_repo }}
    state: latest
  tags:
    - deploy
